title: "Lorenzo — Portfolio"
description: "Software Developer • University of Arizona"
theme: minima

# These pages will show in the top nav bar (minima feature)
header_pages:
  - projects.md
  - about.md
  - contact.md
  
# Optional: social links shown in footer (minima feature)
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/YOUR-USERNAME" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/YOUR-LINKEDIN/" }
